/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jxl.Cell;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;
import static main.FcreateEtudiant.etu;

/**
 *
 * @author berriau
 */
public class FcreateResponsable extends javax.swing.JFrame {

    public static Responsable resp;
    
    /**
     * Creates new form createPersonne
     */
    public FcreateResponsable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom :");

        jLabel2.setText("Prénom :");

        jLabel4.setText("Mail :");

        jLabel5.setText("Responsable");

        jTextField1.setText("Nom");

        jTextField2.setText("Prénom");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("Mail");

        jButton1.setText("S'enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Entreprise :");

        jTextField4.setText("Entreprise");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6))
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField3))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(jLabel5))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /* tom  */
        
       String nom =jTextField1.getText();
       String prenom =jTextField2.getText();
       String mail =jTextField3.getText();
       String entreprise =jTextField4.getText();
       
         
       jxl.write.Number NbEtu;
       
       int erreur=0;
       
       
       
       WritableWorkbook workbook = null;
       //Workbook wSourceResp = null;
       File fSourceResp=new File("BDD/resp.xls");

       
        try {
                /* On créé un nouveau worbook et on l'ouvre en écriture */
                
                Workbook wSourceResp = Workbook.getWorkbook(fSourceResp);
                
                System.out.println("Le fichier excel a été chargé. ");
                
                
                WritableWorkbook copy = Workbook.createWorkbook(fSourceResp,wSourceResp); 
                System.out.println("Le fichier excel peut être modifié. ");

                /* On récupère la feuille etu et on l'ouvre en écriture */
                WritableSheet sheet = copy.getSheet("resp"); 
                
                /* On récupère les mail et les num étudiant pour avoir l'unicité */
                Cell tNumE = sheet.findCell(Integer.toString(numE));
                Cell tMailE =sheet.findCell(mail);
                
                if (tNumE != null ||tMailE != null){
                    System.out.println("Mail ou numéro d'étudiant déjà existant.");
                    //pop up d'erreur
                    javax.swing.JOptionPane.showMessageDialog(null,"Mail ou numéro d'étudiant déjà existant.","Mail ou numéro d'étudiant déjà existant.",JOptionPane.ERROR_MESSAGE);

                    wSourceResp.close();  
                    copy.write();
                    copy.close();    
                    
                    /* on indique l'erreur */
                    erreur=1;
                    
                }
                else {
                    
                    /* on incrémente le nombre d'étudiant */
                    int nbEtudiant =Integer.parseInt(sheet.getCell(5,0).getContents())+1;
                    NbEtu = new jxl.write.Number(5, 0, nbEtudiant);
                    sheet.addCell(NbEtu);
                    
                    /* Creatation du x étudiant */ 
                    Label lNomE = new Label(0, nbEtudiant, nom);
                    sheet.addCell(lNomE);

                    Label lPrenomE = new Label(1, nbEtudiant, prenom);
                    sheet.addCell(lPrenomE);

                    Label lMailE = new Label(2, nbEtudiant, mail);
                    sheet.addCell(lMailE);

                    jxl.write.Number lNumEE = new jxl.write.Number(3, nbEtudiant, numE);
                    sheet.addCell(lNumEE);

                    wSourceResp.close();
                    copy.write();
                    copy.close();

                    etu=new Etudiant(nom,prenom,mail,numE);
                    if(etu.getNom() == null ||etu.getPrenom()==null ||etu.getMail()==null){
                        /* on indique l'erreur */
                        erreur=1;
                        System.out.println("Erreur de format dans vos informations");
                        javax.swing.JOptionPane.showMessageDialog(null,"Problème format","Problème format",JOptionPane.ERROR_MESSAGE);

                    }
                    else{
                        System.out.println("Bienvenu "+etu.getPrenom()+" "+etu.getNom());
                    }


                     /* Creation d'un champ au format numerique */
                     /*Number number = new Number(0, 1, 3.1459);
                     sheet.addCell(number); 
                     */
                }

        } 
        catch (IOException exp) {
            System.out.println("Le fichier excel abscent du dossier, création d'un fichier de stockage Etudiant");
           try {
                workbook = Workbook.createWorkbook(fSourceResp);
               
               /* On créé une nouvelle feuille (test en position 0) et on l'ouvre en écriture */
                WritableSheet sheet = workbook.createSheet("etu", 0); 

                /* Creation de l'en-tête*/
                Label lNom = new Label(0, 0, "Nom");
                sheet.addCell(lNom);
                
                Label lPrenom = new Label(1, 0, "Prénom");
                sheet.addCell(lPrenom);
                
                Label lMail = new Label(2, 0, "Mail");
                sheet.addCell(lMail);
                
                Label lNumE = new Label(3, 0, "NumEtu");
                sheet.addCell(lNumE);
               
                /* on incrémente le nombre d'étudiant */
                NbEtu = new jxl.write.Number(5, 0, 1);
                sheet.addCell(NbEtu);
                
               /* Creatation du premier étudiant */ 
                Label lNomE = new Label(0, 1, nom);
                sheet.addCell(lNomE);
                
                Label lPrenomE = new Label(1, 1, prenom);
                sheet.addCell(lPrenomE);
                
                Label lMailE = new Label(2, 1, mail);
                sheet.addCell(lMailE);
                
                jxl.write.Number lNumEE = new jxl.write.Number(3, 1, numE);
                sheet.addCell(lNumEE);
                
                /* On ecrit le classeur */
                workbook.write();
                
                
               //message d'erreur de base
               //exp.printStackTrace();
           } catch (IOException | WriteException ex) {
               Logger.getLogger(FcreateEtudiant.class.getName()).log(Level.SEVERE, null, ex);
           }
        }  catch (BiffException ex) {
            Logger.getLogger(FcreateEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(FcreateEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally {
                if(workbook!=null){
                        /* On ferme le worbook pour libérer la mémoire */
                        try {
                                workbook.close();
                                etu=new Etudiant(nom,prenom,mail,numE);
                                if(etu.getNom() == null ||etu.getPrenom()==null ||etu.getMail()==null){
                                    /* on indique l'erreur */
                                    erreur=1;
                                    System.out.println("Erreur de format dans vos informations");
                                    javax.swing.JOptionPane.showMessageDialog(null,"Problème format","Problème format",JOptionPane.ERROR_MESSAGE);

                                }
                                else{
                                    System.out.println("Bienvenu "+etu.getPrenom()+" "+etu.getNom());
                                }
                        } 
                        catch (WriteException | IOException exp) {
                            System.out.println("Erreur Workbook");
                        } 
                }
        }
        
        this.dispose();
        try {
            if(erreur==0){
                new Fmain(etu).setVisible(true);
            }
            else{   
                new Findex().setVisible(true);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FcreateEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FcreateResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FcreateResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FcreateResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FcreateResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FcreateResponsable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
